name: Node.js Package

on:
  push:
    tags:
      - '*'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm config set registry https://registry.npmjs.org/
      - run: npm ci
      - run: npx nx run-many -t publish --ver 1.0.0 --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}